[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -c gunicorn.conf.py run:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
